1)
Датасет - Iris species.

2)
Размер - 150 строк.
Все признаки числовые.
Нет пропусков данных.
В датасете 50 строк с данными Iris-setosa, 50 с Iris-versicolor и 50 с Iris-virginica. Данные в датасете хорошо сбалансированы.

In [279]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
import numpy as np

df = pandas.read_csv("Iris.csv")
df.set_index("Id", inplace=True)
df

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm         Species
Id
1              5.1           3.5            1.4           0.2     Iris-setosa
2              4.9           3.0            1.4           0.2     Iris-setosa
3              4.7           3.2            1.3           0.2     Iris-setosa
4              4.6           3.1            1.5           0.2     Iris-setosa
5              5.0           3.6            1.4           0.2     Iris-setosa
..             ...           ...            ...           ...             ...
146            6.7           3.0            5.2           2.3  Iris-virginica
147            6.3           2.5            5.0           1.9  Iris-virginica
148            6.5           3.0            5.2           2.0  Iris-virginica
149            6.2           3.4            5.4           2.3  Iris-virginica
150            5.9           3.0            5.1           1.8  Iris-virginica

[150 rows x 5 columns]

In [280]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   SepalLengthCm  150 non-null    float64
 1   SepalWidthCm   150 non-null    float64
 2   PetalLengthCm  150 non-null    float64
 3   PetalWidthCm   150 non-null    float64
 4   Species        150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [281]:
df.describe(include="all")

        SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
count      150.000000    150.000000     150.000000    150.000000          150
unique            NaN           NaN            NaN           NaN            3
top               NaN           NaN            NaN           NaN  Iris-setosa
freq              NaN           NaN            NaN           NaN           50
mean         5.843333      3.054000       3.758667      1.198667          NaN
std          0.828066      0.433594       1.764420      0.763161          NaN
min          4.300000      2.000000       1.000000      0.100000          NaN
25%          5.100000      2.800000       1.600000      0.300000          NaN
50%          5.800000      3.000000       4.350000      1.300000          NaN
75%          6.400000      3.300000       5.100000      1.800000          NaN
max          7.900000      4.400000       6.900000      2.500000          NaN

3.
Пропусков в датасете нет. Категориальный признак один, и это target столбец. Он не будет учавствовать в обучении, так что применим Label Encoding. ну и заодно сразу разделим датасет на Features и Target. Масштабировать ничего не надо, так как все признаки лежат примерно в одном диапазоне.

In [282]:
labelencoder = LabelEncoder()
y = labelencoder.fit_transform(df["Species"])
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [283]:
X = df.copy().drop(["Species"], axis=1)
X

     SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Id
1              5.1           3.5            1.4           0.2
2              4.9           3.0            1.4           0.2
3              4.7           3.2            1.3           0.2
4              4.6           3.1            1.5           0.2
5              5.0           3.6            1.4           0.2
..             ...           ...            ...           ...
146            6.7           3.0            5.2           2.3
147            6.3           2.5            5.0           1.9
148            6.5           3.0            5.2           2.0
149            6.2           3.4            5.4           2.3
150            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

Далее разделим данные на train, validation и test.

Выделение test:

In [284]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, train_size=0.8, random_state=0, stratify=y)

Выделение validation:

In [285]:
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.25, train_size=0.75, random_state=0, stratify=y_train)

Для kNN важно масштабирование, так как оно уравнивает важность признаков.

Если подбирать параметр на тестовой выборке, то можно переобучить модель. Это происходит потому что параметр подгоняется под определенные данные. Поэтому на test выборке нельзя подбирать параметры. А чтобы не подбирать их "на глаз" на тренировочной выборке, можно разделить датасет на train, validation и test, что я и сделал выше. Тогда можно на validation выборке чуть точнее подобрать параметр, а на test выборке проверить работоспособность модели. Однако и этого может быть мало, тогда можно использовать кросс-валидацию и прочее.

In [ ]:
X_tr = np.array([[1, 2, 3],
         [3, 2, 1],
         [0, 4, 5]])
X_targ = np.array([[0, 1, 0],
           [1, 2, 0]])

n = X_targ.shape[1]
m = X_tr.shape[0]
l = X_targ.shape[0]
C = np.empty((n, m, l))
for i in range(0, n):
    a = X_tr[:, i]
    A = np.array([a] * l).T
    b = X_targ[:, i]
    B = np.array([b] * m)
    
    C[i] = (B - A) ** 2
D = np.sqrt(np.sum(C, axis=0))
D

array([[3.31662479, 3.        ],
       [3.31662479, 2.23606798],
       [5.83095189, 5.47722558]])